baseurl = "https://www.shahrukhomar.com/"
languageCode = "en-gb"
Title = "Shahrukh Omar"
copyright = "&copy; Shahrukh Omar"
theme = "hugo_theme_pickles"
publishDir = "../"
enableEmoji = true

# syntax highlight
pygmentsStyle = "tango"
pygmentsCodeFences = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and footer
  twitter = "shahrukhomar"
  github = "shak"
  npm = "shahrukhomar"
  rss = "/index.xml"
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  # author = "Shahrukh Omar"
  authorwebsite = "https://www.shahrukhomar.com"
  # avatar = "img/logo.png"
  # contact = "Your contact link (ex. mailto:foo@example.com)"
  # bio = "Your short bio"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Blog"
  # Logo image. This is displayed ogp image.
  # logo = "/img/logo.png"
  favicon = "/img/favicon.ico"
